### PR TITLE
Update Spanish translations

### PR DESCRIPTION
**Pull request by FerBueroTrebino**
Spanish translations updated!

### CODE REVIEW

**Comment by lukestokes** [comment]
Any chance you could merge this into dev instead of staging?

**Comment by FerBueroTrebino** [comment]
No problem, i just did it. Can you still merge this into staging?

Thanks!

**Comment by lukestokes** [comment]
Sorry, looks like you merged to master, not dev.

Here's the process:

1) Merge to dev
2) Once we test on dev and we're confident with the changes, we merge all those changes together into staging. If we merge individual things into staging, it creates merge conflicts later which become  big pain to manage.
3) Once we're comfortable with all that and we've done testing on master, we then merge staging into master. Again, if we commit things directly to master, it creates merge conflicts.

**Comment by lukestokes** [comment]
Okay, I think I have the latest changes form this PR and the other put into the file here: https://github.com/eosdac/eosdactoolkit/blob/dev/eosdac-material/src/i18n/es/index.js

If any additional changes are need, please do a pull request into dev or just let me know which changes have to be made and I'll do them manually.

Thanks!

**Pull request closed without merging**
